version: 2

sources:
  - name: headout_sources


    tables:
      - name: wallet_credits_added
        description: "raw table for json transaction payloads for adding credits"
        columns:
          - name: transaction
            description: "json transaction payload"
          - name: loaded_at
            description: "timestamp when the transaction was loaded in raw table"

      - name: wallet_credits_reedemed
        description: "raw table for json transaction payloads for redeeming credits"
        columns:
          - name: transaction
            description: "json transaction payload"
          - name: loaded_at
            description: "timestamp when the transaction was loaded in raw table"

  